stages:
- build

before_script: 
    - git submodule update --init --recursive

osx:
    stage: build
    script: 
        - atbuild test
    tags:
        - openswift
        - atbuild
    artifacts:
        paths:
            - .atllbuild/products/xcode-emit
