stages:
- build

before_script: 
    - git submodule update --init --recursive

osx:
    stage: build
    script: 
        - atbuild check
        - mkdir xcode-emit-${CI_BUILD_REF}
        - cp bin/xcode-emit xcode-emit-${CI_BUILD_REF}
        - tar cJf xcode-emit-${CI_BUILD_REF}-osx.tar.xz xcode-emit-${CI_BUILD_REF}
    tags:
        - openswift
        - atbuild

    artifacts:
        paths:
            - xcode-emit-${CI_BUILD_REF}-osx.tar.xz
