stages:
- build

before_script: 
    - git submodule update --init --recursive

osx:
    stage: build
    script: 
        - atbuild check
        - atbuild package --configuration release
    tags:
        - openswift
        - atbuild

    artifacts:
        paths:
            - bin/xcode_emit*.tar.xz
            - bin/xcode-emit.rb
